### ISSUE TITLE
Not actually on MELPA?

### ISSUE THREAD

**Issue by ylluminarious** [damon-kwok/v-mode#1]
I tried installing this package from MELPA, but I don't see it anywhere. Searching for it on MELPA shows nothing. [The link in the README file](http://melpa.org/#/v-mode) takes you to a 404 page. Is it actually on MELPA or does it need to be manually installed right now?

**Comment by damon-kwok** [comment]
@ylluminarious 
I submitted a PR and awaiting merger.
See:
https://github.com/melpa/melpa/pull/7031

**Comment by ylluminarious** [comment]
@damon-kwok Thanks! 🙇

**Comment by damon-kwok** [comment]
@ylluminarious v-mode has been deployed to MELPA.

**Comment by ylluminarious** [comment]
@damon-kwok Thanks so much!
