### ISSUE TITLE
wrong auto-mode-alist regexp

### ISSUE THREAD

**Issue by jibal** [damon-kwok/v-mode#10]
The regexp "\\.v?v\\.vsh\\'" in v-mode.el and README.md is incorrect -- that matches .v.vsh or .vv.vsh ... the correct pattern is
 "\\.v\\(v?\\|sh\\)\\'"

**Comment by jibal** [comment]
P.S. This was pointed out in issue #2 which was closed without fixing it, and is probably also the problem in issue #9

**Comment by damon-kwok** [comment]
@jibal Fixed
https://github.com/damon-kwok/v-mode/blob/a701f4cedfff91cf4bcd17c9a2cd16a49f942743/v-mode.el#L518
