### ISSUE TITLE
v fmt uses // for comments

### ISSUE THREAD

**Issue by rrthomas** [damon-kwok/v-mode#12]
I am using the latest release of `v-mode`. It uses `/*…*/` for comments, but then `v fmt` on saving immediately replaces them with `//` comments. I suggest changing `v-mode` to match `v fmt`.

Thanks for `v-mode`!

**Comment by damon-kwok** [comment]
@rrthomas Yep, that's the recommended usage of vlang.

**Comment by rrthomas** [comment]
Sorry, I don't understand. I am saying that v-mode does not match `v fmt`, and I'm suggesting that you change v-mode to match `v fmt`. Or are you saying that `v fmt` is wrong?

**Comment by damon-kwok** [comment]
I'll see how I can change `v-mode` to the one recommended by `v fmt`.

**Comment by damon-kwok** [comment]
@rrthomas Fixed

**Comment by rrthomas** [comment]
Thanks very much for the quick fix and release, already installed from MELPA in my Emacs!
