### ISSUE TITLE
ctags question

### ISSUE THREAD

**Issue by xandro0777** [damon-kwok/v-mode#8]
ctags is called with ```--languages=-v``` - is there a ctags version that understands this option?

**Comment by damon-kwok** [comment]
@xandro0777 This is to exclude user directory definitions.

**Comment by xandro0777** [comment]
Thanks for the explanation.

On my system this parameter causes a 2 line warning message which is slightly irritating as it doesn't fit into  the minibuffer and causes it to expand. Maybe this warning should be filtered out and not displayed?

**Comment by damon-kwok** [comment]
Removed

**Comment by philippludwig** [comment]
Now it is using the option `--langdef=v`, but the irritating warning message remains, unless you install `exuberant-ctags`.
