### ISSUE TITLE
Indentation and company completion not working

### ISSUE THREAD

**Issue by wbehrens-on-gh** [damon-kwok/v-mode#9]
After following the install tutorial for use-package and sraight.el I'm not getting any auto completion and emacs is wanting to indent 12 spaces

* **Version**:  27.2
* **Platform**: Linux void 5.13.19_1 1 SMP Sat Sep 18 18:18:26 UTC 2021 x86_64 GNU/Linux

**Comment by damon-kwok** [comment]
Please provide the output of emacs...
And, have you tried installing with <kbd>M-x package-install [RET] v-mode [RET] </kbd>? Did you get the same result?
If convenient, please attach a screenshot.
